// @ts-nocheck — Seed script: crea el catalogo global de leyes.
// Ya no crea usuario demo ni partida demo — el registro es via /registro
// y las partidas se crean desde el wizard autenticado.
import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { buildPoolConfig } from "../src/lib/db-config";

// Misma conexión que la app (DATABASE_URL, DATABASE_SSL, pool…): ver src/lib/db-config.ts
const adapter = new PrismaPg(buildPoolConfig());
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log("🌱 Iniciando seed (catalogo de leyes)...");
  // Idempotente: se puede ejecutar contra una base con datos sin borrar nada (upsert por `key`).

  const leyes = [
    { key: "subsidio-alimentario", name: "Subsidio Alimentario", description: "Programa de subsidio directo para alimentos basicos a familias de bajos recursos.", effectsJson: { povertyRate: -5, approval: { EXTREME_POVERTY: 8, POVERTY: 4, MIDDLE: -1, ELITE: -2 } }, idealIdeology: { economic: -60, social: 40, authority: -10 }, cost: 500000000 },
    { key: "impuesto-progresivo", name: "Impuesto Progresivo a la Renta", description: "Sistema impositivo donde los que mas ganan pagan mayor porcentaje.", effectsJson: { taxRevenue: 15, approval: { EXTREME_POVERTY: 5, POVERTY: 3, MIDDLE: 0, ELITE: -8 }, gini: -3 }, idealIdeology: { economic: -70, social: 30, authority: 0 }, cost: 0 },
    { key: "ley-anticorrupcion", name: "Ley Anticorrupcion Integral", description: "Endurece penas por corrupcion y crea mecanismos de control.", effectsJson: { corruption: -10, transparency: 15, approval: { EXTREME_POVERTY: 3, POVERTY: 3, MIDDLE: 5, ELITE: -2 } }, idealIdeology: { economic: 0, social: 30, authority: 0 }, cost: 200000000 },
    { key: "servicio-militar-obligatorio", name: "Servicio Militar Obligatorio", description: "Establece el servicio militar obligatorio para jovenes de 18 anios.", effectsJson: { defenseEfficiency: 10, approval: { EXTREME_POVERTY: -2, POVERTY: -5, MIDDLE: -3, ELITE: 2 }, civilLiberties: -5 }, idealIdeology: { economic: 20, social: -30, authority: 50 }, cost: 300000000 },
    { key: "educacion-publica-gratuita", name: "Educacion Publica Gratuita Universal", description: "Garantiza acceso gratuito a todos los niveles educativos.", effectsJson: { educationLevel: 15, approval: { EXTREME_POVERTY: 8, POVERTY: 7, MIDDLE: 5, ELITE: -1 } }, idealIdeology: { economic: -30, social: 60, authority: 0 }, cost: 800000000 },
    { key: "salud-universal", name: "Sistema de Salud Universal", description: "Cobertura medica garantizada para todos los ciudadanos.", effectsJson: { sickRate: -8, approval: { EXTREME_POVERTY: 10, POVERTY: 8, MIDDLE: 6, ELITE: -1 } }, idealIdeology: { economic: -40, social: 50, authority: 0 }, cost: 1000000000 },
    { key: "liberalizacion-economica", name: "Liberalizacion Economica", description: "Reduce regulaciones, aranceles y barreras comerciales.", effectsJson: { gdp: 10, taxRevenue: -5, approval: { EXTREME_POVERTY: -5, POVERTY: -3, MIDDLE: 2, ELITE: 8 }, gini: 5 }, idealIdeology: { economic: 80, social: -20, authority: -30 }, cost: 0 },
    { key: "estado-emergencia", name: "Estado de Emergencia Nacional", description: "Otorga poderes especiales al ejecutivo para manejar crisis.", effectsJson: { civilLiberties: -15, powerConcentration: 10, approval: { EXTREME_POVERTY: 0, POVERTY: -2, MIDDLE: -5, ELITE: 5 } }, idealIdeology: { economic: 30, social: -40, authority: 80 }, cost: 100000000 },
    { key: "reforma-judicial", name: "Reforma del Poder Judicial", description: "Reestructura el sistema judicial para mayor independencia.", effectsJson: { judicialIndependence: 20, corruption: -5, approval: { EXTREME_POVERTY: 2, POVERTY: 3, MIDDLE: 5, ELITE: 0 } }, idealIdeology: { economic: 0, social: 40, authority: -20 }, cost: 400000000 },
    { key: "ley-transparencia", name: "Ley de Transparencia y Acceso a la Informacion", description: "Obliga al gobierno a publicar todos sus actos y gastos.", effectsJson: { transparency: 20, corruption: -8, approval: { EXTREME_POVERTY: 2, POVERTY: 3, MIDDLE: 6, ELITE: 2 } }, idealIdeology: { economic: -10, social: 50, authority: -30 }, cost: 100000000 },
    { key: "libertad-prensa", name: "Libertad de Prensa Garantizada", description: "Prohibe la censura estatal y protege a periodistas.", effectsJson: { pressFreedom: 25, approval: { EXTREME_POVERTY: 1, POVERTY: 3, MIDDLE: 7, ELITE: 4 } }, idealIdeology: { economic: -20, social: 70, authority: -50 }, cost: 50000000 },
    { key: "censura-medios", name: "Ley de Regulacion de Contenidos Mediaticos", description: "Permite al gobierno controlar contenidos 'perjudiciales' en medios.", effectsJson: { pressFreedom: -20, powerConcentration: 10, approval: { EXTREME_POVERTY: -1, POVERTY: -3, MIDDLE: -8, ELITE: 2 } }, idealIdeology: { economic: 30, social: -60, authority: 70 }, cost: 50000000 },
    { key: "reforma-constitucional", name: "Reforma Constitucional", description: "Modifica articulos clave de la constitucion para cambiar el equilibrio de poderes.", effectsJson: { powerConcentration: 15, judicialIndependence: -10, politicalPluralism: -5, approval: { EXTREME_POVERTY: -2, POVERTY: -3, MIDDLE: -6, ELITE: 5 } }, idealIdeology: { economic: 10, social: -20, authority: 60 }, cost: 100000000 },
    { key: "despenalizacion-aborto", name: "Despenalizacion del Aborto", description: "Elimina las sanciones penales por interrupcion del embarazo.", effectsJson: { approval: { EXTREME_POVERTY: -1, POVERTY: 0, MIDDLE: 5, ELITE: 3 }, civilLiberties: 10 }, idealIdeology: { economic: -10, social: 80, authority: -30 }, cost: 0 },
    { key: "ley-antimonopolios", name: "Ley Anti-Monopolios y Competencia", description: "Impide la concentracion excesiva de mercado y promueve competencia.", effectsJson: { gdp: 5, gini: -4, approval: { EXTREME_POVERTY: 3, POVERTY: 4, MIDDLE: 3, ELITE: -6 } }, idealIdeology: { economic: -30, social: 20, authority: 0 }, cost: 150000000 },

    // ── Nuevas leyes (fase 2) ──────────────────────────────────────────────
    { key: "reforma-policial", name: "Reforma Policial", description: "Reestructura las fuerzas de seguridad con mejor entrenamiento y control interno.", effectsJson: { crimeRate: -8, civilLiberties: -3, powerConcentration: 3, monthlyCost: 400000000, approval: { EXTREME_POVERTY: -1, POVERTY: -2, MIDDLE: 4, ELITE: 5 } }, idealIdeology: { economic: 10, social: -10, authority: 30 }, cost: 400000000 },
    { key: "reforma-agraria", name: "Reforma Agraria", description: "Redistribuye tierras improductivas a pequenos agricultores y campesinos.", effectsJson: { foodSecurity: 10, povertyRate: -3, monthlyCost: 300000000, approval: { EXTREME_POVERTY: 10, POVERTY: 8, MIDDLE: 2, ELITE: -8 } }, idealIdeology: { economic: -60, social: 30, authority: -10 }, cost: 300000000 },
    { key: "privatizacion-empresas", name: "Privatizacion de Empresas Publicas", description: "Vende empresas estatales al sector privado para reducir el gasto publico.", effectsJson: { gdp: 8, gini: 3, unemploymentRate: 2, taxRevenue: 8, approval: { EXTREME_POVERTY: -3, POVERTY: -5, MIDDLE: 2, ELITE: 10 } }, idealIdeology: { economic: 80, social: -10, authority: -20 }, cost: -2000000000 },
    { key: "control-precios", name: "Control de Precios", description: "Establece precios maximos para productos de primera necesidad.", effectsJson: { inflation: -5, gdp: -3, foodSecurity: 3, monthlyCost: 100000000, approval: { EXTREME_POVERTY: 8, POVERTY: 6, MIDDLE: 2, ELITE: -5 } }, idealIdeology: { economic: -50, social: 20, authority: 30 }, cost: 100000000 },
    { key: "amnistia-fiscal", name: "Amnistia Fiscal", description: "Permite regularizar capitales no declarados con una tasa reducida por 24 meses.", effectsJson: { taxRevenue: 15, transparency: -5, approval: { EXTREME_POVERTY: -1, POVERTY: -1, MIDDLE: 2, ELITE: 8 } }, idealIdeology: { economic: 60, social: -20, authority: 0 }, cost: 50000000 },
    { key: "ley-proteccion-ambiental", name: "Ley de Proteccion Ambiental", description: "Impone limites de emisiones y crea areas naturales protegidas.", effectsJson: { sickRate: -3, foodSecurity: 5, gdp: -2, monthlyCost: 350000000, approval: { EXTREME_POVERTY: 2, POVERTY: 3, MIDDLE: 6, ELITE: -3 } }, idealIdeology: { economic: -20, social: 60, authority: -10 }, cost: 350000000 },
    { key: "reforma-previsional", name: "Reforma Previsional", description: "Crea un sistema de pensiones solidario con cobertura universal.", effectsJson: { povertyRate: -4, monthlyCost: 800000000, approval: { EXTREME_POVERTY: 10, POVERTY: 8, MIDDLE: 6, ELITE: -8 } }, idealIdeology: { economic: -40, social: 50, authority: -10 }, cost: 800000000 },
    { key: "inversion-extranjera", name: "Ley de Inversion Extranjera", description: "Ofrece garantias y beneficios fiscales a inversores internacionales.", effectsJson: { gdp: 10, gini: 2, unemploymentRate: -5, monthlyCost: 200000000, approval: { EXTREME_POVERTY: -2, POVERTY: 0, MIDDLE: 3, ELITE: 8 } }, idealIdeology: { economic: 70, social: -10, authority: -30 }, cost: 200000000 },
    { key: "plan-vivienda", name: "Plan Nacional de Vivienda", description: "Construye viviendas sociales y otorga creditos blandos para primera vivienda.", effectsJson: { povertyRate: -3, unemploymentRate: -2, monthlyCost: 600000000, approval: { EXTREME_POVERTY: 10, POVERTY: 8, MIDDLE: 5, ELITE: -2 } }, idealIdeology: { economic: -30, social: 50, authority: 0 }, cost: 600000000 },
    { key: "reeleccion-indefinida", name: "Reeleccion Indefinida", description: "Elimina el limite constitucional de mandatos para el ejecutivo.", effectsJson: { powerConcentration: 10, politicalPluralism: -10, approval: { EXTREME_POVERTY: -2, POVERTY: -2, MIDDLE: -5, ELITE: 3 } }, idealIdeology: { economic: 20, social: -30, authority: 80 }, cost: 50000000 },

    // ── Leyes inspiradas en eventos reales ──────────────────────────────────
    { key: "plan-control-territorial", name: "Plan Control Territorial", description: "Regimen de excepcion con despliegue militar masivo para combatir el crimen organizado. Inspirado en El Salvador.", effectsJson: { crimeRate: -12, civilLiberties: -8, powerConcentration: 5, monthlyCost: 500000000, approval: { EXTREME_POVERTY: 5, POVERTY: 6, MIDDLE: 4, ELITE: 3 } }, idealIdeology: { economic: 20, social: -30, authority: 60 }, cost: 500000000 },
    { key: "ley-patriota", name: "Ley Patriota", description: "Amplia los poderes de vigilancia estatal y agencias de inteligencia para prevenir amenazas. Inspirada en EEUU.", effectsJson: { crimeRate: -5, civilLiberties: -10, powerConcentration: 5, monthlyCost: 300000000, approval: { EXTREME_POVERTY: -1, POVERTY: -2, MIDDLE: -3, ELITE: 5 } }, idealIdeology: { economic: 30, social: -50, authority: 70 }, cost: 300000000 },
    { key: "policia-comunitaria", name: "Policia Comunitaria", description: "Modelo de policia de proximidad con agentes integrados en los barrios. Inspirado en el sistema Koban japones.", effectsJson: { crimeRate: -4, civilLiberties: 3, monthlyCost: 200000000, approval: { EXTREME_POVERTY: 6, POVERTY: 5, MIDDLE: 4, ELITE: 2 } }, idealIdeology: { economic: 0, social: 30, authority: -20 }, cost: 200000000 },
    { key: "operacion-lava-jato", name: "Operacion Lava Jato", description: "Investigacion masiva anticorrupcion con fiscales y jueces independientes. Inspirada en Brasil.", effectsJson: { corruption: -15, judicialIndependence: 10, monthlyCost: 100000000, approval: { EXTREME_POVERTY: 5, POVERTY: 6, MIDDLE: 3, ELITE: -8 } }, idealIdeology: { economic: 0, social: 40, authority: -10 }, cost: 100000000 },
    { key: "extincion-dominio", name: "Ley de Extincion de Dominio", description: "Confisca bienes adquiridos ilicitamente sin necesidad de sentencia penal firme. Inspirada en Peru y Colombia.", effectsJson: { corruption: -8, transparency: 5, approval: { EXTREME_POVERTY: 4, POVERTY: 5, MIDDLE: 4, ELITE: -5 } }, idealIdeology: { economic: -10, social: 20, authority: 20 }, cost: -500000000 },
    { key: "contraloria-ciudadana", name: "Contraloria Ciudadana", description: "Auditoria social con participacion de la ciudadania en la fiscalizacion del gasto publico.", effectsJson: { transparency: 10, corruption: -5, monthlyCost: 150000000, approval: { EXTREME_POVERTY: 3, POVERTY: 4, MIDDLE: 5, ELITE: -2 } }, idealIdeology: { economic: -10, social: 50, authority: -20 }, cost: 150000000 },
    { key: "autogolpe-constitucional", name: "Autogolpe Constitucional", description: "Disuelve el Congreso por decreto ejecutivo y concentra el poder. Inspirado en el autogolpe de Fujimori en Peru.", effectsJson: { powerConcentration: 20, judicialIndependence: -15, politicalPluralism: -20, civilLiberties: -10, approval: { EXTREME_POVERTY: -2, POVERTY: -2, MIDDLE: -8, ELITE: 5 } }, idealIdeology: { economic: 20, social: -50, authority: 90 }, cost: 50000000 },
    { key: "reforma-penal-acusatoria", name: "Reforma Penal Acusatoria", description: "Transforma el sistema de justicia de inquisitivo a acusatorio con juicios orales y transparentes. Inspirada en Chile.", effectsJson: { judicialIndependence: 15, crimeRate: -3, transparency: 5, monthlyCost: 450000000, approval: { EXTREME_POVERTY: 2, POVERTY: 3, MIDDLE: 5, ELITE: 2 } }, idealIdeology: { economic: 0, social: 40, authority: -20 }, cost: 450000000 },
    { key: "tribunal-constitucional", name: "Tribunal Constitucional Autonomo", description: "Crea un tribunal supremo independiente para revisar la constitucionalidad de las leyes. Inspirado en Corea del Sur.", effectsJson: { judicialIndependence: 15, politicalPluralism: 5, monthlyCost: 200000000, approval: { EXTREME_POVERTY: 1, POVERTY: 2, MIDDLE: 6, ELITE: 3 } }, idealIdeology: { economic: 0, social: 30, authority: -30 }, cost: 200000000 },
    { key: "abenomics", name: "Abenomics", description: "Programa de estimulo economico agresivo con politica monetaria expansiva y gasto fiscal. Inspirado en Japon.", effectsJson: { gdp: 10, inflation: 3, unemploymentRate: -5, treasury: -1000000000, approval: { EXTREME_POVERTY: 3, POVERTY: 4, MIDDLE: 5, ELITE: 3 } }, idealIdeology: { economic: -20, social: 10, authority: 10 }, cost: 1000000000 },
    { key: "economia-planificada", name: "Economia Planificada", description: "Control estatal de los medios de produccion y planificacion central. Inspirada en el modelo cubano.", effectsJson: { povertyRate: -8, foodSecurity: 5, gdp: -8, gini: -4, monthlyCost: 500000000, approval: { EXTREME_POVERTY: 10, POVERTY: 7, MIDDLE: -3, ELITE: -10 } }, idealIdeology: { economic: -80, social: 10, authority: 60 }, cost: 500000000 },
    { key: "zonas-economicas-especiales", name: "Zonas Economicas Especiales", description: "Crea enclaves economicos con regulacion flexible para atraer inversion extranjera. Inspirado en las reformas de Deng Xiaoping en China.", effectsJson: { gdp: 15, gini: 4, unemploymentRate: -5, monthlyCost: 400000000, approval: { EXTREME_POVERTY: -2, POVERTY: 0, MIDDLE: 3, ELITE: 10 } }, idealIdeology: { economic: 70, social: -10, authority: -40 }, cost: 400000000 },
    { key: "reforma-afp", name: "Reforma del Sistema de Pensiones (AFP)", description: "Privatiza el sistema de pensiones con cuentas de capitalizacion individual. Inspirada en el modelo chileno.", effectsJson: { gdp: 5, gini: 3, povertyRate: 2, approval: { EXTREME_POVERTY: -3, POVERTY: -2, MIDDLE: 0, ELITE: 8 } }, idealIdeology: { economic: 70, social: -20, authority: -10 }, cost: -3000000000 },
    { key: "mision-salud-comunitaria", name: "Mision Salud Comunitaria", description: "Despliega medicos en zonas vulnerables con atencion gratuita casa por casa. Inspirada en las misiones cubanas y venezolanas.", effectsJson: { sickRate: -8, monthlyCost: 700000000, approval: { EXTREME_POVERTY: 10, POVERTY: 8, MIDDLE: 5, ELITE: -2 } }, idealIdeology: { economic: -30, social: 40, authority: -10 }, cost: 700000000 },
    { key: "becas-merito", name: "Becas Universales por Merito", description: "Inversion masiva en educacion superior con becas completas para los mejores estudiantes. Inspirado en Corea del Sur.", effectsJson: { educationLevel: 12, gdp: 3, monthlyCost: 900000000, approval: { EXTREME_POVERTY: 8, POVERTY: 7, MIDDLE: 6, ELITE: 1 } }, idealIdeology: { economic: -10, social: 50, authority: 0 }, cost: 900000000 },
    { key: "politica-hijo-unico", name: "Politica de Hijo Unico", description: "Restringe la natalidad por decreto estatal para controlar el crecimiento poblacional. Inspirada en China.", effectsJson: { population: -2, gdp: 3, civilLiberties: -8, approval: { EXTREME_POVERTY: -5, POVERTY: -5, MIDDLE: -3, ELITE: 2 } }, idealIdeology: { economic: 10, social: -40, authority: 80 }, cost: 50000000 },
    { key: "estimulo-natalidad", name: "Estimulo a la Natalidad", description: "Subsidios por hijo, licencia parental extendida y guarderias publicas para fomentar la natalidad. Inspirado en Japon y Corea del Sur.", effectsJson: { unemploymentRate: -2, monthlyCost: 600000000, approval: { EXTREME_POVERTY: 8, POVERTY: 8, MIDDLE: 7, ELITE: 2 } }, idealIdeology: { economic: -30, social: 60, authority: -10 }, cost: 600000000 },
    { key: "reforma-urbana", name: "Reforma Urbana Integral", description: "Renovacion de centros urbanos, iluminacion, espacios publicos y vivienda social. Inspirada en las reformas de Bukele.", effectsJson: { crimeRate: -4, povertyRate: -2, foodSecurity: 2, monthlyCost: 500000000, approval: { EXTREME_POVERTY: 7, POVERTY: 7, MIDDLE: 5, ELITE: -1 } }, idealIdeology: { economic: -20, social: 30, authority: 20 }, cost: 500000000 },
  ];

  for (const ley of leyes) {
    await prisma.lawCatalog.upsert({ where: { key: ley.key }, create: ley, update: ley });
  }
  console.log(`  ✓ ${leyes.length} leyes en catalogo`);

  console.log("\n✅ Seed completado.");
}

main()
  .catch((e) => {
    console.error("❌ Error en seed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
